import { Dongle } from "next/font/google";
import "./globals.css";

const dongle = Dongle({
    weight: ['300', '400', '700'],
    subsets: ['latin'],
    display: 'swap',
})


export const metadata = {
  title: "Sam Alvarez",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dongle.className}>
      <body>{children}</body>
    </html>
  );
}
